"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import api from "@/lib/api";
export default function RoleLogin({ role, title, destination }: { role: "DESIGNER" | "DEMANDAS"; title: string; destination: string }) {
 const router = useRouter(); const [login, setLogin] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
 const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(""); try { const { data } = await api.post("/auth/login", { login, password }); if (data.user?.role !== role) { setError("Este acesso é exclusivo para o portal selecionado."); return; } localStorage.setItem("token", data.token); localStorage.setItem("user", JSON.stringify(data.user)); router.push(destination); } catch (e: any) { setError(e.response?.data?.error || "Credenciais inválidas"); } finally { setLoading(false); } };
 return <main className="flex min-h-screen items-center justify-center bg-slate-950 p-4 text-white"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-white/10 bg-white/5 p-8 shadow-2xl"><p className="text-xs font-bold uppercase tracking-[.2em] text-blue-300">Acesso restrito</p><h1 className="mt-2 text-3xl font-semibold">{title}</h1><p className="mt-2 text-sm text-slate-400">Entre para registrar e acompanhar seus serviços.</p>{error && <p className="mt-5 rounded-xl bg-red-500/15 p-3 text-sm text-red-200">{error}</p>}<label className="mt-6 block text-sm">E-mail ou celular<input required value={login} onChange={e => setLogin(e.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-slate-900 p-3"/></label><label className="mt-4 block text-sm">Senha<input required type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-slate-900 p-3"/></label><button disabled={loading} className="mt-6 w-full rounded-xl bg-blue-600 p-3 font-semibold hover:bg-blue-500 disabled:opacity-50">{loading ? "Entrando..." : "Entrar"}</button></form></main>;
}
